In [1]:
import numpy as np

# Load the file
FCD = np.load("sub-0001_0.04_1.89_0.005_FCD.txt.npy")

# Check the shape and type
print("Type:", type(FCD))
print("Shape:", FCD.shape)

# Optionally, print a small part of the array
print(FCD[:5, :5])  # prints the first 5x5 block

Type: <class 'numpy.ndarray'>
Shape: (17, 17)
[[1.         0.67732195 0.43581319 0.34407676 0.22522006]
 [0.67732195 1.         0.77211461 0.60284911 0.40308797]
 [0.43581319 0.77211461 1.         0.8020787  0.52187703]
 [0.34407676 0.60284911 0.8020787  1.         0.68242465]
 [0.22522006 0.40308797 0.52187703 0.68242465 1.        ]]


In [2]:
import numpy as np

# Load the file
FCD = np.load("sub-0001_0.04_2.2115076488_0.005_FCD.txt.npy")

# Check the shape and type
print("Type:", type(FCD))
print("Shape:", FCD.shape)

# Optionally, print a small part of the array
print(FCD[:5, :5])  # prints the first 5x5 block

Type: <class 'numpy.ndarray'>
Shape: (17, 17)
[[1.         0.57915072 0.38893262 0.29863192 0.20743542]
 [0.57915072 1.         0.77939669 0.66969545 0.56125433]
 [0.38893262 0.77939669 1.         0.86298238 0.73977883]
 [0.29863192 0.66969545 0.86298238 1.         0.88238033]
 [0.20743542 0.56125433 0.73977883 0.88238033 1.        ]]
